name: Moai SDK
highlighter: rouge
markdown: redcarpet
baseurl: /community-docs
exclude: [.gitignore, Gemfile, Gemfile.lock, params.json, README.md, build-scripts]

collections:
  docs:
    output: true

defaults:
  -
    scope:
      path: ""
      type: docs
    values:
      layout: doc
      order: 0
